### ISSUE TITLE
Double reply

### ISSUE THREAD

**Issue by jjstables** [Nokeo08/standardsbot#9]
Check out [this comment.](https://www.reddit.com/r/Reformed/comments/5i4gv4/iama_very_devout_old_catholicanglocatholic_ive/db5c3dh/) Standardsbot replied twice with WCF 27:5.

Nothing terribly odd about the formatting of the original comment, and it wasn't edited/re-saved at any point. The doubled replies came at 12:22:22 and 12:22:57.

**Comment by Nokeo08** [comment]
Went back and looked through the logs and I do not have a log for the 27:5 reference but I do for the 27:4 that was immediately after that. I looked through the error logs and it looks like the reddit api has been responding with 503 errors a lot recently which has caused crashes. The supervisor deamon I have running has restarted the StandardsBot process, but if the crash happened after the response and before the logging of it the bot could double respond. I plan on trying to change the logging pattern I am using to stop crashes from bad api responses. This happens a lot, but it would just catch the error and keep running. It will not things like this from happening. I'm not sure how to avoid this. If I move the logging then if this kind of error happens again then instead of double replying it could just not reply at all. I think I'd rather the former edge case than the latter.

**Comment by jjstables** [comment]
Makes sense. And I did mean 27:4 Just can't see logging so I couldn't rule out an unintentional issue.
